name: CI Build all products

on:
  workflow_dispatch:

jobs:
  fetch-builds:
    name: "Fetch FxServer Builds"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-builds.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - run: node ./fetch-builds.mjs >> $GITHUB_OUTPUT
        id: find-builds
  create-fxserver-image:
    name: "Create image for build ${{ matrix.build}}"
    runs-on: ubuntu-latest
    needs: [ fetch-builds ]
    if: needs.fetch-builds.outputs.matrix != ''
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON( needs.fetch-builds.outputs.matrix )}}
    steps:
      - name: Download FxServer
        run: curl -o fx.tar.xz ${{ matrix.url }}
      - name: Decompress archive
        run: tar -xf fx.tar.xz alpine 
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images          
        uses: docker/build-push-action@v6.7.0
        with:
          push: false
          tags: "vaksdk/fxserver:${{ matrix.build_id }}"

